
/*search*/
const SEARCH_SEARCH='SEARCH_SEARCH';
const SEARCH_HIT='SEARCH_HIT';
const SEARCH_GUESSCUSTOMERLIKE='SEARCH_GUESSCUSTOMERLIKE';
const SEARCH_ADVICESEARCH='SEARCH_ADVICESEARCH';
const SEARCH_GETSEARCHSTORAGE='SEARCH_GETSEARCHSTORAGE';
const SEARCH_LOADMORE='SEARCH_LOADMORE';
const SEARCH_REFRESHDATA='SEARCH_REFRESHDATA';

/*account*/
const ACCOUNT_LOGIN ='ACCOUNT_LOGIN';
const ACCOUNT_LOGINOUT='ACCOUNT_LOGINOUT';

/*home*/
const HOME_GETNEWS='HOME_GETNEWS';
const HOME_LOADMORE='HOME_LOADMORE';
const HOME_REFRESHDATA='HOME_REFRESHDATA';
const HOME_GETSEARCHSTORAGE='HOME_GETSEARCHSTORAGE';
const HOME_GETADVICETABLIST='HOME_GETADVICETABLIST';

/*video*/
const VIDEO_GETVIDEOS='VIDEO_GETVIDEOS';
const VIDEO_LOADMORE='VIDEO_LOADMORE';
const VIDEO_REFRESHDATA='VIDEO_REFRESHDATA';
const VIDEO_GETSEARCHSTORAGE='VIDEO_GETSEARCHSTORAGE';

/*findPerson*/
const FINDPERSON_GETFENLEILIST='FINDPERSON_GETFENLEILIST';
const FINDPERSON_GETPERSONBARINFO='FINDPERSON_GETPERSONBARINFO';

export default {
	SEARCH_SEARCH,
	SEARCH_HIT,
	SEARCH_GUESSCUSTOMERLIKE,
	SEARCH_ADVICESEARCH,
	SEARCH_GETSEARCHSTORAGE,
	SEARCH_LOADMORE,
	SEARCH_REFRESHDATA,

	ACCOUNT_LOGIN,
	ACCOUNT_LOGINOUT,

	HOME_GETNEWS,
	HOME_LOADMORE,
	HOME_REFRESHDATA,
	HOME_GETSEARCHSTORAGE,
	HOME_GETADVICETABLIST,

	VIDEO_GETVIDEOS,
	VIDEO_LOADMORE,
	VIDEO_REFRESHDATA,
	VIDEO_GETSEARCHSTORAGE,

    FINDPERSON_GETFENLEILIST,
    FINDPERSON_GETPERSONBARINFO
}